### ISSUE TITLE
(p59) 데이터 베이스 연결에서 막힙니다..

### ISSUE THREAD

**Issue by rotmdwo** [benimario/parayo-api#1]
안녕하세요, 책의 코드를 따라가다 막히는 부분이 있어서 질문드립니다..
페이지 59쪽에 Mysql과 연결하는 하는 부분에서 계속 실패하네요..

에러 코드는 
Unable to determine jdbc url from datasource
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
mysql java.net.ConnectException: Connection refused
java.sql.SQLNonTransientConnectionException: Could not create connection to database server.

등이 나옵니다..
책의 내용에 따라 aws에서 데이터베이스도 구축했고, 컴퓨터에 설치한 mysql에서 통신이 되는 것도 확인했습니다.
코드도 책에서 제시한대로 그대로 했는데(driver-class-name은 com.mysql.cj.jdbc.Driver로 바꾸라고 나와서 바꿨습니다.)도 안 됩니다..

혹시 방법이 있을까요? 감사합니다.

**Comment by benimario** [comment]
안녕하세요.
먼저 RDS 의 퍼블릭 액세스 가능 여부와 보안그룹의 인바운드 규칙 목록을 공유해주실 수 있을까요?

**Comment by rotmdwo** [comment]
안녕하세요, 빠른 피드백 감사드립니다.
해당 이미지 첨부하겠습니다.
참고로 aws DB 버전은 5.7.26으로 먼저 설치하였다가
로컬에 mysql을 설치할 때 아카이브에 5.7.26 버전이 없어서
8.0.16으로 설치하였습니다. 위와 같은 에러가 버전이 달라서 생기는 문제일까봐
현재 aws DB의 버전도 8.0.16으로 업그레이드 한 상태입니다.
감사합니다.
<br>
<img src="https://drive.google.com/uc?export=view&id=1-7wdvtzBZTtoNKl--0me0tcXIqZ9EE_M"  onerror="this.style.display='none'" /><br><br>
<img src="https://drive.google.com/uc?export=view&id=1YW5RqgIkisJMcZg-Y9oXx7ft2QqGb47C"  onerror="this.style.display='none'" /><br><br>
<br>
(수정)
spring -> datasource -> url을 jdbc:mysql://127.0.0.1:3306/... 에서
jdbc:mysql://kotlin-server-learning.cbaymlj1afih.us-east-2.rds.amazonaws.com3306/... 이렇게 aws 엔드포인트로 바꾸니까
실행이 되었습니다. 이럴 경우 Intellij와 Mysql 간에 통신을 못하는 건가요? 인터넷 검색했을 때는 방화벽 문제일 수도 있다고 본 것 같아서요..
감사합니다.
<br>

**Comment by benimario** [comment]
127.0.0.1 은 내 컴퓨터의 로컬 IP 입니다.
이 경우 로컬에 mysql 이 실행 중이어야 하고 RDS 를 사용하시려면 수정하신대로 RDS 주소를 이용하시면 됩니다.

**Comment by rotmdwo** [comment]
감사합니다.
